image: continuumio/miniconda3:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
            - conda
          script:
            - conda env update -n ci-meta-exporter --file bitbucket-environment.yml
            - conda activate ci-meta-exporter
            - pip install -e ./python/
            - export CI_META_PREFIX=cf-index-meta-data
            - export CI_META_VERSION=$(ci-meta-exporter -v)
            - echo 'devel' >ci-meta-version.txt
            - export CI_META_NAME=${CI_META_PREFIX}-${CI_META_VERSION}
            - mkdir $CI_META_NAME
            - cp master_table.xls README.md LICENSE.txt $CI_META_NAME
            - cd $CI_META_NAME
            - ci-meta-exporter ./master_table.xls
            - cd ..
            - tar cvf ${CI_META_PREFIX}-devel.tar.gz $CI_META_NAME
            - cd $CI_META_NAME
            - unix2dos README.md LICENSE.txt *.yml
            - cd ..
            - zip -r ${CI_META_PREFIX}-devel.zip $CI_META_NAME
          artifacts:
            - 'ci-meta-version.txt'
            - 'cf-index-meta-data-*.tar.gz'
            - 'cf-index-meta-data-*.zip'
      - step:
          name: Deploy to test
          deployment: Test
          script:
            - export CI_META_VERSION=$(cat ci-meta-version.txt)
            - pipe: atlassian/bitbucket-upload-file:0.1.4
              variables:
                BITBUCKET_USERNAME: kzimmer
                BITBUCKET_APP_PASSWORD: $BB_AUTH_STRING
                FILENAME: cf-index-meta-data-${CI_META_VERSION}.tar.gz
            - pipe: atlassian/bitbucket-upload-file:0.1.4
              variables:
                BITBUCKET_USERNAME: kzimmer
                BITBUCKET_APP_PASSWORD: $BB_AUTH_STRING
                FILENAME: cf-index-meta-data-${CI_META_VERSION}.zip

  tags:
    cf-index-meta-*:
      - step:
          caches:
            - pip
            - conda
          script:
            - conda env update -n ci-meta-exporter --file bitbucket-environment.yml
            - conda activate ci-meta-exporter
            - pip install -e ./python/
            - export CI_META_PREFIX=cf-index-meta-data
            - export CI_META_VERSION=$(ci-meta-exporter -v)
            - echo $CI_META_VERSION >ci-meta-version.txt
            - export CI_META_NAME=${CI_META_PREFIX}-${CI_META_VERSION}
            - mkdir $CI_META_NAME
            - cp master_table.xls README.md LICENSE.txt $CI_META_NAME
            - cd $CI_META_NAME
            - ci-meta-exporter ./master_table.xls
            - cd ..
            - tar cvf ${CI_META_NAME}.tar.gz $CI_META_NAME
            - cd $CI_META_NAME
            - unix2dos README.md LICENSE.txt *.yml
            - cd ..
            - zip -r ${CI_META_NAME}.zip $CI_META_NAME
          artifacts:
            - 'ci-meta-version.txt'
            - 'cf-index-meta-data-*.tar.gz'
            - 'cf-index-meta-data-*.zip'
      - step:
          name: Deploy to staging
          deployment: Staging
          script:
            - export CI_META_VERSION=$(cat ci-meta-version.txt)
            - pipe: atlassian/bitbucket-upload-file:0.1.4
              variables:
                BITBUCKET_USERNAME: kzimmer
                BITBUCKET_APP_PASSWORD: $BB_AUTH_STRING
                FILENAME: cf-index-meta-data-${CI_META_VERSION}.tar.gz
            - pipe: atlassian/bitbucket-upload-file:0.1.4
              variables:
                BITBUCKET_USERNAME: kzimmer
                BITBUCKET_APP_PASSWORD: $BB_AUTH_STRING
                FILENAME: cf-index-meta-data-${CI_META_VERSION}.zip

definitions:
  caches:
    conda:  ~/.conda/envs/ci-meta-exporter
